/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northandromeda.proyecto;

import java.awt.Color;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import static northandromeda.proyecto.Pobladordemapas.pobladorMapaCursos;

/**
 *
 * @author yorch
 */
public class PanelbuscarAlumno extends javax.swing.JPanel {
    
    /**
     * Creates new form panelbuscarAlumno
     */
    public PanelbuscarAlumno() {
        initComponents();
    }
       
    
    private Color azulClaro = new Color(71,125,205);
    private Color azul = new Color(47,99,176);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelVerificador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        labelMaterias = new javax.swing.JLabel();
        campoCurso = new javax.swing.JTextField();
        labelCurso = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        campoRut = new javax.swing.JTextField();
        LabelTextoRut = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVerificador.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(labelVerificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 20));

        tablaNotas.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"calan", "1"}
            },
            new String [] {
                "Asignaturas", "notas"
            }
        ));
        tablaNotas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaNotas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 610, 310));

        labelMaterias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMaterias.setText("Materias");
        jPanel1.add(labelMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 23));

        campoCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoCurso.setEnabled(false);
        jPanel1.add(campoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 200, -1));

        labelCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCurso.setText("Curso");
        jPanel1.add(labelCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 100, 23));

        campoNombre.setEnabled(false);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        labelNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNombre.setText("Nombre");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 23));

        botonBuscar.setBackground(new java.awt.Color(47, 99, 176));

        labelBuscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonBuscarLayout = new javax.swing.GroupLayout(botonBuscar);
        botonBuscar.setLayout(botonBuscarLayout);
        botonBuscarLayout.setHorizontalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        botonBuscarLayout.setVerticalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        campoRut.setText("Ingrese rut");
        campoRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoRutMouseClicked(evt);
            }
        });
        campoRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRutActionPerformed(evt);
            }
        });
        jPanel1.add(campoRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, -1));

        LabelTextoRut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelTextoRut.setText("Rut del alumno");
        jPanel1.add(LabelTextoRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 20));

        Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Titulo.setText("BUSCAR ALUMNO");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 10));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void campoRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRutActionPerformed

    private void campoRutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoRutMouseClicked
        // TODO add your handling code here:
        if(campoRut.getText().equals("Ingrese su rut")){
            campoRut.setText("");
            campoRut.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoRutMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked

        if(!campoRut.getText().equals("")){
            Alumno current ;
            try {
                labelVerificador.setText("");

                current = Busqueda.buscarAlumno(campoRut.getText());
                campoNombre.setText(current.getNombre());
                campoCurso.setText(current.getCursodeAlumno());

            } catch (IOException ex) {
                Logger.getLogger(PanelbuscarAlumno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            labelVerificador.setText("INGRESE RUT VALIDO");
        }
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTextoRut;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JTextField campoCurso;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoRut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelMaterias;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelVerificador;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
