/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northandromeda.proyecto;

import java.awt.Color;
import java.util.ArrayList;
import static northandromeda.proyecto.CSV.notasAlumno;

/**
 *
 * @author yorch
 */
public class PanelbuscarAlumno extends javax.swing.JPanel {
    
    /**
     * Creates new form panelbuscarAlumno
     */
    public PanelbuscarAlumno() {
        initComponents();
    }
       
    
    private Color azulClaro = new Color(71,125,205);
    private Color azul = new Color(47,99,176);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMaterias = new javax.swing.JLabel();
        labelNombreTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelCursoTitulo = new javax.swing.JLabel();
        labelCurso = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botonBuscar = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        campoRut = new javax.swing.JTextField();
        LabelTextoRut = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        labelMateriaTitulo = new javax.swing.JLabel();
        labelMateria = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMaterias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMaterias.setText("Notas:");
        jPanel1.add(labelMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 100, 23));

        labelNombreTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNombreTitulo.setText("Nombre:");
        jPanel1.add(labelNombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, 23));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 340, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 340, 10));

        labelCursoTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCursoTitulo.setText("Curso:");
        jPanel1.add(labelCursoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, 23));

        labelCurso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(labelCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 340, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 340, 10));

        botonBuscar.setBackground(new java.awt.Color(47, 99, 176));

        labelBuscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscar.setText("Buscar");
        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBuscarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout botonBuscarLayout = new javax.swing.GroupLayout(botonBuscar);
        botonBuscar.setLayout(botonBuscarLayout);
        botonBuscarLayout.setHorizontalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        botonBuscarLayout.setVerticalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 20));

        campoRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoRutMouseClicked(evt);
            }
        });
        campoRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRutActionPerformed(evt);
            }
        });
        jPanel1.add(campoRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, -1));

        LabelTextoRut.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelTextoRut.setText("Rut del alumno");
        jPanel1.add(LabelTextoRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 20));

        Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Titulo.setText("BUSCAR ALUMNO");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 10));

        tablaNotas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "EVALUACIONES", "NOTAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaNotas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaNotas.setEditingColumn(0);
        tablaNotas.setEditingRow(0);
        tablaNotas.setEnabled(false);
        jScrollPane1.setViewportView(tablaNotas);
        if (tablaNotas.getColumnModel().getColumnCount() > 0) {
            tablaNotas.getColumnModel().getColumn(0).setResizable(false);
            tablaNotas.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 510, 110));

        labelMateriaTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMateriaTitulo.setText("Materia:");
        jPanel1.add(labelMateriaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 23));

        labelMateria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(labelMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 340, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 340, 10));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Datos del Alumno:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Nota: Rut con puntos y guion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 10));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nota: el promedio podria no ser el final");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 500, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void campoRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRutActionPerformed

    private void campoRutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoRutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRutMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        Alumno current = null ;
        
        
        if(Busqueda.buscarAlumno(campoRut.getText())!=null){
            
            current = Busqueda.buscarAlumno(campoRut.getText());
            labelNombre.setText(current.getNombre());
            labelCurso.setText(current.getCursodeAlumno());
            labelMateria.setText(VentanaInicio.profe.getMateria());
            ArrayList<String> notas = notasAlumno(current.getRut(),VentanaInicio.profe.getMateria()+".csv");
            current.setPromedio();
            
            if (notas != null){
                tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                    {"evaluacion 1", notas.get(0)},
                    {"evaluacion 2", notas.get(1)},
                    {"evaluacion 3", notas.get(2)},
                    {"evaluacion 4", notas.get(3)},
                    {"evaluacion 5", notas.get(4)},
                    {"Promedio", current.getPromedio()}
                    },
                    new String [] {
                        "EVALUACIONES", "NOTAS"
                    }
                ));
            }else{
                tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                    {"evaluacion 1", "0"},
                    {"evaluacion 2", "0"},
                    {"evaluacion 3", "0"},
                    {"evaluacion 4", "0"},
                    {"evaluacion 5", "0"},
                    {"Promedio", "0"}
                    },
                    new String [] {
                        "EVALUACIONES", "NOTAS"
                    }
                ));
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "RUT INVALIDO ", "Error de lectura",  javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void labelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseEntered
        botonBuscar.setBackground(azulClaro);
    }//GEN-LAST:event_labelBuscarMouseEntered

    private void labelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseExited
        botonBuscar.setBackground(azul);
    }//GEN-LAST:event_labelBuscarMouseExited

    private void labelBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMousePressed
        botonBuscar.setBackground(azul);
    }//GEN-LAST:event_labelBuscarMousePressed

    private void labelBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseReleased
        botonBuscar.setBackground(azulClaro);
    }//GEN-LAST:event_labelBuscarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTextoRut;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JTextField campoRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelCursoTitulo;
    private javax.swing.JLabel labelMateria;
    private javax.swing.JLabel labelMateriaTitulo;
    private javax.swing.JLabel labelMaterias;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreTitulo;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
