/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northandromeda.proyecto;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.HashMap;
import static northandromeda.proyecto.Pobladordemapas.pobladorMapaCursos;

/**
 *
 * @author yorch
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    
    
    public VentanaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);//ventana aparesca al centro
        
        PanelPrincipal current = new PanelPrincipal();
        current.setSize(contenido.getSize());
        current.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(current,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    
    
    private Color azulClaro = new Color(71,125,205);
    private Color azul = new Color(47,99,176);
    
    //paleta de colores
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgorund = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        botonPrincipal = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        labelPrincipal = new javax.swing.JLabel();
        botonCurso = new javax.swing.JPanel();
        labelBotonCurso = new javax.swing.JLabel();
        botonBuscarAl = new javax.swing.JPanel();
        labelBuscarAl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botonAñadirAl = new javax.swing.JPanel();
        labelBotonAñadirAl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonListaprofes = new javax.swing.JPanel();
        labelMateria = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        botonSalir = new javax.swing.JPanel();
        labelsalir = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgorund.setBackground(new java.awt.Color(255, 255, 255));
        backgorund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIzquierdo.setBackground(new java.awt.Color(47, 99, 176));
        panelIzquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMenu.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu.setText("MENU");
        panelIzquierdo.add(labelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 80));

        botonPrincipal.setBackground(new java.awt.Color(47, 99, 176));
        botonPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        botonPrincipal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 290, -1));

        labelPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        labelPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrincipal.setText("Principal");
        labelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPrincipalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPrincipalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelPrincipalMouseReleased(evt);
            }
        });
        botonPrincipal.add(labelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        panelIzquierdo.add(botonPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 70));

        botonCurso.setBackground(new java.awt.Color(47, 99, 176));
        botonCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBotonCurso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelBotonCurso.setForeground(new java.awt.Color(255, 255, 255));
        labelBotonCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBotonCurso.setText("Lista de cursos");
        labelBotonCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBotonCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBotonCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBotonCursoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBotonCursoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBotonCursoMouseReleased(evt);
            }
        });
        botonCurso.add(labelBotonCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        panelIzquierdo.add(botonCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 70));

        botonBuscarAl.setBackground(new java.awt.Color(47, 99, 176));
        botonBuscarAl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscarAl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBuscarAl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelBuscarAl.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscarAl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscarAl.setText("Buscar Alumno");
        labelBuscarAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarAlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBuscarAlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBuscarAlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBuscarAlMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBuscarAlMouseReleased(evt);
            }
        });
        botonBuscarAl.add(labelBuscarAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));
        botonBuscarAl.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        panelIzquierdo.add(botonBuscarAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 70));

        botonAñadirAl.setBackground(new java.awt.Color(47, 99, 176));
        botonAñadirAl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAñadirAl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBotonAñadirAl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelBotonAñadirAl.setForeground(new java.awt.Color(255, 255, 255));
        labelBotonAñadirAl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBotonAñadirAl.setText("Añadir Alumno");
        labelBotonAñadirAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBotonAñadirAlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBotonAñadirAlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBotonAñadirAlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBotonAñadirAlMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBotonAñadirAlMouseReleased(evt);
            }
        });
        botonAñadirAl.add(labelBotonAñadirAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));
        botonAñadirAl.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        panelIzquierdo.add(botonAñadirAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 70));

        botonListaprofes.setBackground(new java.awt.Color(47, 99, 176));
        botonListaprofes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonListaprofes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMateria.setForeground(new java.awt.Color(255, 255, 255));
        labelMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMateria.setText("Editar Notas");
        labelMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMateriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMateriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMateriaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMateriaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelMateriaMouseReleased(evt);
            }
        });
        botonListaprofes.add(labelMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));
        botonListaprofes.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        panelIzquierdo.add(botonListaprofes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 70));

        botonSalir.setBackground(new java.awt.Color(47, 99, 176));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelsalir.setForeground(new java.awt.Color(255, 255, 255));
        labelsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsalir.setText("SALIR");
        labelsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelsalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelsalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelsalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelsalirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelsalirMouseReleased(evt);
            }
        });
        botonSalir.add(labelsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        panelIzquierdo.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 70));

        backgorund.add(panelIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 620));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        backgorund.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 650, 620));

        getContentPane().add(backgorund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void labelBotonCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonCursoMouseEntered
        // TODO add your handling code here:
        botonCurso.setBackground(azulClaro);
    }//GEN-LAST:event_labelBotonCursoMouseEntered

    private void labelBotonCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonCursoMouseExited
        // TODO add your handling code here:
        botonCurso.setBackground(azul);
    }//GEN-LAST:event_labelBotonCursoMouseExited

    private void labelBotonCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonCursoMouseClicked
        /*
        -----------------Lista curso------------------
        */
        PanelListaCurso current = new PanelListaCurso();
        current.setSize(contenido.getSize());
        current.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(current,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_labelBotonCursoMouseClicked

    private void labelBotonCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonCursoMousePressed
        // TODO add your handling code here:
        botonCurso.setBackground(azul);
    }//GEN-LAST:event_labelBotonCursoMousePressed

    private void labelBotonCursoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonCursoMouseReleased
        // TODO add your handling code here:
        botonCurso.setBackground(azulClaro);
    }//GEN-LAST:event_labelBotonCursoMouseReleased

    private void labelBotonAñadirAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonAñadirAlMouseClicked
        /*
        -----------------Añadir Alumno------------------
        */
        PanelAñadirAlumno current = new PanelAñadirAlumno();
        current.setSize(650,620);
        current.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(current,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_labelBotonAñadirAlMouseClicked

    private void labelBotonAñadirAlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonAñadirAlMouseEntered
        // TODO add your handling code here:
        botonAñadirAl.setBackground(azulClaro);
    }//GEN-LAST:event_labelBotonAñadirAlMouseEntered

    private void labelBotonAñadirAlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonAñadirAlMouseExited
        // TODO add your handling code here:
        botonAñadirAl.setBackground(azul);
    }//GEN-LAST:event_labelBotonAñadirAlMouseExited

    private void labelBotonAñadirAlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonAñadirAlMousePressed
        // TODO add your handling code here:
        botonAñadirAl.setBackground(azul);
    }//GEN-LAST:event_labelBotonAñadirAlMousePressed

    private void labelBotonAñadirAlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonAñadirAlMouseReleased
        // TODO add your handling code here:
        botonAñadirAl.setBackground(azulClaro);
    }//GEN-LAST:event_labelBotonAñadirAlMouseReleased

    private void labelBuscarAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarAlMouseClicked
        /*
        -----------------Buscar Alumno------------------
        */
        
        PanelbuscarAlumno current = new PanelbuscarAlumno();
        current.setSize(contenido.getSize());
        current.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(current,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
        
    }//GEN-LAST:event_labelBuscarAlMouseClicked

    private void labelBuscarAlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarAlMouseEntered
        // TODO add your handling code here:
        botonBuscarAl.setBackground(azulClaro);
    }//GEN-LAST:event_labelBuscarAlMouseEntered

    private void labelBuscarAlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarAlMouseExited
        // TODO add your handling code here:
        botonBuscarAl.setBackground(azul);
    }//GEN-LAST:event_labelBuscarAlMouseExited

    private void labelBuscarAlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarAlMousePressed
        // TODO add your handling code here:
        botonBuscarAl.setBackground(azul);
    }//GEN-LAST:event_labelBuscarAlMousePressed

    private void labelBuscarAlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarAlMouseReleased
        // TODO add your handling code here:
        botonBuscarAl.setBackground(azulClaro);
    }//GEN-LAST:event_labelBuscarAlMouseReleased

    private void labelMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMateriaMouseClicked
        /*
        -----------------Materias------------------
        */
        PanelMateria current = new PanelMateria();
        current.setSize(contenido.getSize());
        current.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(current,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_labelMateriaMouseClicked

    private void labelMateriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMateriaMouseEntered
        // TODO add your handling code here:
        botonListaprofes.setBackground(azulClaro);
    }//GEN-LAST:event_labelMateriaMouseEntered

    private void labelMateriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMateriaMouseExited
        // TODO add your handling code here:
        botonListaprofes.setBackground(azul);
    }//GEN-LAST:event_labelMateriaMouseExited

    private void labelMateriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMateriaMousePressed
        // TODO add your handling code here:
        botonListaprofes.setBackground(azul);
    }//GEN-LAST:event_labelMateriaMousePressed

    private void labelMateriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMateriaMouseReleased
        // TODO add your handling code here:
        botonListaprofes.setBackground(azulClaro);
    }//GEN-LAST:event_labelMateriaMouseReleased

    private void labelPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrincipalMouseClicked
        // TODO add your handling code here:
       PanelPrincipal current = new PanelPrincipal();
        current.setSize(contenido.getSize());
        current.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(current,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_labelPrincipalMouseClicked

    private void labelPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrincipalMouseEntered
        // TODO add your handling code here:
        botonPrincipal.setBackground(azulClaro);
    }//GEN-LAST:event_labelPrincipalMouseEntered

    private void labelPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrincipalMouseExited
        // TODO add your handling code here:
        botonPrincipal.setBackground(azul);
    }//GEN-LAST:event_labelPrincipalMouseExited

    private void labelPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrincipalMousePressed
        // TODO add your handling code here:
        botonPrincipal.setBackground(azul);
    }//GEN-LAST:event_labelPrincipalMousePressed

    private void labelPrincipalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrincipalMouseReleased
        // TODO add your handling code here:
        botonPrincipal.setBackground(azulClaro);
    }//GEN-LAST:event_labelPrincipalMouseReleased

    private void labelsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelsalirMouseClicked

    private void labelsalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsalirMouseEntered
        // TODO add your handling code here:
        botonSalir.setBackground(azulClaro);
    }//GEN-LAST:event_labelsalirMouseEntered

    private void labelsalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsalirMouseExited
        // TODO add your handling code here:
        botonSalir.setBackground(azul);
    }//GEN-LAST:event_labelsalirMouseExited

    private void labelsalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsalirMousePressed
        // TODO add your handling code here:
        botonSalir.setBackground(azul);
    }//GEN-LAST:event_labelsalirMousePressed

    private void labelsalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsalirMouseReleased
        // TODO add your handling code here:
        botonSalir.setBackground(azulClaro);
    }//GEN-LAST:event_labelsalirMouseReleased

    public static void ron(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgorund;
    private javax.swing.JPanel botonAñadirAl;
    private javax.swing.JPanel botonBuscarAl;
    private javax.swing.JPanel botonCurso;
    private javax.swing.JPanel botonListaprofes;
    private javax.swing.JPanel botonPrincipal;
    private javax.swing.JPanel botonSalir;
    private javax.swing.JPanel contenido;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelBotonAñadirAl;
    private javax.swing.JLabel labelBotonCurso;
    private javax.swing.JLabel labelBuscarAl;
    private javax.swing.JLabel labelMateria;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelPrincipal;
    private javax.swing.JLabel labelsalir;
    private javax.swing.JPanel panelIzquierdo;
    // End of variables declaration//GEN-END:variables
}
