/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northandromeda.proyecto;

import java.util.HashMap;
import static northandromeda.proyecto.Busqueda.buscarAlumno2;
import static northandromeda.proyecto.Pobladordemapas.pobladorMapaCursos;

/**
 *
 * @author yorch
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }
    
    
    private boolean lc=false,lp=false,ba=false,aa=false;
    /*
    
    booleanos para saber que opcion es la que se esta considerando
    lc:lista cursos
    lp:lista profe
    ba:buscar alumno
    aa:añadir alumno
    
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgorund = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonAnadirAl = new javax.swing.JButton();
        botonBuscarAl = new javax.swing.JButton();
        botonListadecursos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextPane();
        botonConsola = new javax.swing.JButton();
        campoConsola = new javax.swing.JTextField();
        labelConsola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgorund.setBackground(new java.awt.Color(255, 255, 255));
        backgorund.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgorund.setDoubleBuffered(false);
        backgorund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(71, 125, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 210, 53));

        botonAnadirAl.setText("añadir alumno");
        botonAnadirAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnadirAlMouseClicked(evt);
            }
        });
        botonAnadirAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirAlActionPerformed(evt);
            }
        });
        jPanel1.add(botonAnadirAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 53));

        botonBuscarAl.setText("buscar alumno");
        botonBuscarAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarAlMouseClicked(evt);
            }
        });
        botonBuscarAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarAlActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 53));

        botonListadecursos.setText("lista de cursos");
        botonListadecursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListadecursosMouseClicked(evt);
            }
        });
        botonListadecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadecursosActionPerformed(evt);
            }
        });
        jPanel1.add(botonListadecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 53));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 30));

        jButton2.setText("lista de profes");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 53));

        backgorund.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 620));

        jLabel2.setText("CONCEPTO DISEÑO BASE PUEDE CAMBIAR EN EL FUTURO");
        backgorund.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 430, 20));

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setFocusable(false);

        consola.setText("prueba");
        consola.setFocusable(false);
        consola.setHighlighter(null);
        consola.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(consola);

        backgorund.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 560, 430));

        botonConsola.setText("boton de prueba");
        botonConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsolaMouseClicked(evt);
            }
        });
        backgorund.add(botonConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 170, -1));

        campoConsola.setText("Campo de prueba");
        backgorund.add(campoConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 210, -1));

        labelConsola.setText("Label de prueba");
        backgorund.add(labelConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 110, -1));

        getContentPane().add(backgorund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonBuscarAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarAlActionPerformed

    private void botonListadecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadecursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonListadecursosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonAnadirAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirAlActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonAnadirAlActionPerformed

    private void botonListadecursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListadecursosMouseClicked
        // TODO add your handling code here:
        
        String linea="";
        linea+="";
        consola.setText("");
        
        lc=true;
        lp=false;
        ba=false;
        aa=false;
        
        campoConsola.setVisible(true);
        campoConsola.setText("");
        labelConsola.setVisible(true);
        labelConsola.setText("Ingrese la opcion tal cual esta en la consola:");
        botonConsola.setText("opcion aun en desarollo");
        
    }//GEN-LAST:event_botonListadecursosMouseClicked

    private void botonBuscarAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarAlMouseClicked
        // TODO add your handling code here:
        consola.setText("");
        
        lc=false;
        lp=false;
        ba=true;
        aa=false;
        
        campoConsola.setVisible(true);
        campoConsola.setText("");
        labelConsola.setVisible(true);
        labelConsola.setText("Ingresar rut del alumno (con guion y puntos):");
        botonConsola.setText("buscar alumno");
    }//GEN-LAST:event_botonBuscarAlMouseClicked

    private void botonAnadirAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirAlMouseClicked
        // TODO add your handling code here:
        consola.setText("");
        
        lc=false;
        lp=false;
        ba=false;
        aa=true;
        
        campoConsola.setVisible(true);
        campoConsola.setText("");
        labelConsola.setVisible(true);
        labelConsola.setText("Ingresar rut del alumno (con guion y puntos):");
        botonConsola.setText("opcion aun en desarollo");
    }//GEN-LAST:event_botonAnadirAlMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        consola.setText("");
        
        lc=false;
        lp=true;
        ba=false;
        aa=false;
        
        campoConsola.setVisible(false);
        campoConsola.setText("");
        labelConsola.setVisible(false);
        botonConsola.setText("mostrar lista");
    }//GEN-LAST:event_jButton2MouseClicked

    private void botonConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsolaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsolaMouseClicked

    public static void ron () {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgorund;
    private javax.swing.JButton botonAnadirAl;
    private javax.swing.JButton botonBuscarAl;
    private javax.swing.JButton botonConsola;
    private javax.swing.JButton botonListadecursos;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoConsola;
    private javax.swing.JTextPane consola;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelConsola;
    // End of variables declaration//GEN-END:variables

}
