package northandromeda.proyecto;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class VentanaInicio extends javax.swing.JFrame {
    
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);//ventana aparesca al centro
        RutString.setText("");
        RutString.setForeground(Color.black);
    }
    
    public static Profesor profe;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        textInicio = new javax.swing.JLabel();
        textRut = new javax.swing.JLabel();
        RutString = new javax.swing.JTextField();
        textContra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ClaveString = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        panelBotonInicio = new javax.swing.JPanel();
        LogIn = new javax.swing.JLabel();
        textWarn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(47, 68, 110));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("GESTOR DE EVALUACIONES");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 360, -1));

        textInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textInicio.setText("INICIAR SESION");
        jPanel1.add(textInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, -1));

        textRut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textRut.setText("Rut");
        jPanel1.add(textRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        RutString.setForeground(new java.awt.Color(153, 153, 153));
        RutString.setText("Ingrese su rut");
        RutString.setBorder(null);
        RutString.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RutStringMouseClicked(evt);
            }
        });
        jPanel1.add(RutString, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 280, 20));

        textContra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textContra.setText("Contraseña");
        jPanel1.add(textContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 280, -1));

        ClaveString.setForeground(new java.awt.Color(153, 153, 153));
        ClaveString.setText("**********");
        ClaveString.setBorder(null);
        ClaveString.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClaveStringMouseClicked(evt);
            }
        });
        jPanel1.add(ClaveString, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 280, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 10));

        panelBotonInicio.setBackground(new java.awt.Color(71, 125, 205));

        LogIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogIn.setForeground(new java.awt.Color(244, 244, 244));
        LogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIn.setText("ENTRAR");
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogInMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBotonInicioLayout = new javax.swing.GroupLayout(panelBotonInicio);
        panelBotonInicio.setLayout(panelBotonInicioLayout);
        panelBotonInicioLayout.setHorizontalGroup(
            panelBotonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelBotonInicioLayout.setVerticalGroup(
            panelBotonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelBotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        textWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(textWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 360, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("logo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseEntered
        //dieño para simular un boton 
        //boton reposo = [47,68,110] 
        //cursor sobre el = boton [90,130,190]
        panelBotonInicio.setBackground(new Color(90,130,190));
    }//GEN-LAST:event_LogInMouseEntered

    private void LogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseExited
        panelBotonInicio.setBackground(new Color(71,125,205));
    }//GEN-LAST:event_LogInMouseExited

    private void LogInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMousePressed
        // TODO add your handling code here:
        panelBotonInicio.setBackground(new Color(71,125,205));
    }//GEN-LAST:event_LogInMousePressed

    private void LogInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseReleased
        // TODO add your handling code here:
        panelBotonInicio.setBackground(new Color(90,130,190));
    }//GEN-LAST:event_LogInMouseReleased

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
    
        Profesor current = null;
        
        try {
            //buscamos al profesor
            current = Busqueda.buscarProfesor(RutString.getText());
            
            
            if (current != null){
                
                //verificamos la contraseña
                if (Busqueda.correctPassword(current, ClaveString.getText())){
                    VentanaMenu next = new VentanaMenu();
                    profe = current;
                    this.setVisible(false);
                    next.setVisible(true);
                
                }else{
                    textWarn.setForeground(Color.red);
                    textWarn.setText("Contraseña incorrecta");
                }
            
            }else{
                //si sale esto significa que no esta registrado
                textWarn.setForeground(Color.red);
                textWarn.setText("Usuario no registrado");
            }
            
        } catch (IOException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_LogInMouseClicked

    private void RutStringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RutStringMouseClicked
        
        
        //esto ayuda al diseño de las ventanas
        if(RutString.getText().equals("Ingrese su rut")){
            RutString.setText("");
            RutString.setForeground(Color.black);
        }
        if(String.valueOf(ClaveString.getPassword()).isEmpty()){
            ClaveString.setText("**********");
            ClaveString.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_RutStringMouseClicked

    private void ClaveStringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaveStringMouseClicked
        //esto ayuda al diseño de las ventanas
        if(String.valueOf(ClaveString.getPassword()).equals("**********")){
            ClaveString.setText("");
            ClaveString.setForeground(Color.black);
        }
        if(RutString.getText().isEmpty()){
            RutString.setText("Ingrese su rut");
            RutString.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ClaveStringMouseClicked

    public static void run() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaInicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClaveString;
    private javax.swing.JLabel LogIn;
    private javax.swing.JTextField RutString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelBotonInicio;
    private javax.swing.JLabel textContra;
    private javax.swing.JLabel textInicio;
    private javax.swing.JLabel textRut;
    private javax.swing.JLabel textWarn;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    private boolean buscarProfesor(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
