/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northandromeda.proyecto;

import java.awt.Color;
import java.util.HashMap;
import static northandromeda.proyecto.Pobladordemapas.conjuntoDEprofes;

/**
 *
 * @author yorch
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        campoRut.setText("");
        campoRut.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        textInicio = new javax.swing.JLabel();
        textRut = new javax.swing.JLabel();
        campoRut = new javax.swing.JTextField();
        textContra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        campoContra = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        panelBotonInicio = new javax.swing.JPanel();
        labelBotonIn = new javax.swing.JLabel();
        textWarn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(47, 68, 110));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("GESTOR DE EVALUACIONES");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 360, -1));

        textInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textInicio.setText("INICIAR SESION");
        jPanel1.add(textInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, -1));

        textRut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textRut.setText("Rut");
        jPanel1.add(textRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        campoRut.setForeground(new java.awt.Color(153, 153, 153));
        campoRut.setText("Ingrese su rut");
        campoRut.setBorder(null);
        campoRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoRutMouseClicked(evt);
            }
        });
        jPanel1.add(campoRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 280, 20));

        textContra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textContra.setText("Contraseña");
        jPanel1.add(textContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 280, -1));

        campoContra.setForeground(new java.awt.Color(153, 153, 153));
        campoContra.setText("**********");
        campoContra.setBorder(null);
        campoContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContraMouseClicked(evt);
            }
        });
        jPanel1.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 280, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 10));

        panelBotonInicio.setBackground(new java.awt.Color(71, 125, 205));

        labelBotonIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBotonIn.setForeground(new java.awt.Color(244, 244, 244));
        labelBotonIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBotonIn.setText("ENTRAR");
        labelBotonIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBotonInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBotonInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBotonInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBotonInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBotonInMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBotonInicioLayout = new javax.swing.GroupLayout(panelBotonInicio);
        panelBotonInicio.setLayout(panelBotonInicioLayout);
        panelBotonInicioLayout.setHorizontalGroup(
            panelBotonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBotonIn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelBotonInicioLayout.setVerticalGroup(
            panelBotonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBotonIn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelBotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        textWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(textWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 360, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("logo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelBotonInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonInMouseEntered
        //dieño para simular un boton 
        //boton reposo = [47,68,110] 
        //cursor sobre el = boton [90,130,190]
        panelBotonInicio.setBackground(new Color(90,130,190));
    }//GEN-LAST:event_labelBotonInMouseEntered

    private void labelBotonInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonInMouseExited
        panelBotonInicio.setBackground(new Color(71,125,205));
    }//GEN-LAST:event_labelBotonInMouseExited

    private void labelBotonInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonInMousePressed
        // TODO add your handling code here:
        panelBotonInicio.setBackground(new Color(71,125,205));
    }//GEN-LAST:event_labelBotonInMousePressed

    private void labelBotonInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonInMouseReleased
        // TODO add your handling code here:
        panelBotonInicio.setBackground(new Color(90,130,190));
    }//GEN-LAST:event_labelBotonInMouseReleased

    private void labelBotonInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonInMouseClicked
        // TODO add your handling code here:
        HashMap<String,Profesor> profesores = conjuntoDEprofes();
        //ERROR CONOCIDO: al no poder incluir IOExeption lo marca como error
        //hacer funcion buscarProfesor() para no tener que usar hashmap dentro de la ventana
        
        String rut = campoRut.getText();
        Profesor current = profesores.get(rut);
        
        if(current==null){
            textWarn.setForeground(Color.red);
            textWarn.setText("Usuario y/o contraseña no registrados");
        }else{
            VentanaMenu next = new VentanaMenu();
            this.setVisible(false);
            next.setVisible(true);
        }
        
    }//GEN-LAST:event_labelBotonInMouseClicked

    private void campoRutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoRutMouseClicked
        // TODO add your handling code here:
        if(campoRut.getText().equals("Ingrese su rut")){
            campoRut.setText("");
            campoRut.setForeground(Color.black);
        }
        if(String.valueOf(campoContra.getPassword()).isEmpty()){
            campoContra.setText("**********");
            campoContra.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_campoRutMouseClicked

    private void campoContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraMouseClicked
        // TODO add your handling code here:
        if(String.valueOf(campoContra.getPassword()).equals("**********")){
            campoContra.setText("");
            campoContra.setForeground(Color.black);
        }
        if(campoRut.getText().isEmpty()){
            campoRut.setText("Ingrese su rut");
            campoRut.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_campoContraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContra;
    private javax.swing.JTextField campoRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBotonIn;
    private javax.swing.JPanel panelBotonInicio;
    private javax.swing.JLabel textContra;
    private javax.swing.JLabel textInicio;
    private javax.swing.JLabel textRut;
    private javax.swing.JLabel textWarn;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
